version: '3'

services:
  site:
    build:
      context: .
    working_dir: /site
    network_mode: host
    volumes:
      - ./:/site
      - ../.zsh_history:/root/.zsh_history
    ulimits:
      nofile:
        soft: 999999
        hard: 999999
    command: ["sh", "-c", "[ ! -d node_modules ] && npm install --ignore-scripts && sh /site/patch-equihash.sh && mkdir -p node_modules/verushash && echo 'module.exports={verify:function(){return false;}};' > node_modules/verushash/index.js && npm rebuild; pm2-runtime start ecosystem.config.js --only site"]

  redis:
    image: redis:latest
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ../.redis:/data

# vim:set ts=2 sw=2 smarttab:
